//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("Microsoft.Practices.Common.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string ErrorHelper_Abort {
            get {
                return ResourceManager.GetString("ErrorHelper_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string ErrorHelper_Cancel {
            get {
                return ResourceManager.GetString("ErrorHelper_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Framework Error.
        /// </summary>
        internal static string ErrorHelper_Caption {
            get {
                return ResourceManager.GetString("ErrorHelper_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        internal static string ErrorHelper_HideDetails {
            get {
                return ResourceManager.GetString("ErrorHelper_HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        internal static string ErrorHelper_HideDetailsException {
            get {
                return ResourceManager.GetString("ErrorHelper_HideDetailsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string ErrorHelper_Ignore {
            get {
                return ResourceManager.GetString("ErrorHelper_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string ErrorHelper_No {
            get {
                return ResourceManager.GetString("ErrorHelper_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string ErrorHelper_OK {
            get {
                return ResourceManager.GetString("ErrorHelper_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string ErrorHelper_Retry {
            get {
                return ResourceManager.GetString("ErrorHelper_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string ErrorHelper_ShowDetails {
            get {
                return ResourceManager.GetString("ErrorHelper_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string ErrorHelper_ShowDetailsException {
            get {
                return ResourceManager.GetString("ErrorHelper_ShowDetailsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string ErrorHelper_Yes {
            get {
                return ResourceManager.GetString("ErrorHelper_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can not have an empty value..
        /// </summary>
        internal static string General_ArgumentEmpty {
            get {
                return ResourceManager.GetString("General_ArgumentEmpty", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon2 {
            get {
                object obj = ResourceManager.GetObject("Icon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon3 {
            get {
                object obj = ResourceManager.GetObject("Icon3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon4 {
            get {
                object obj = ResourceManager.GetObject("Icon4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not assignable to type {1}..
        /// </summary>
        internal static string ReflectionHelper_CantAssignTo {
            get {
                return ResourceManager.GetString("ReflectionHelper_CantAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load assembly {0}. Verify if the type {1} syntax is correct..
        /// </summary>
        internal static string ReflectionHelper_CantLoadAssembly {
            get {
                return ResourceManager.GetString("ReflectionHelper_CantLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load type {0}..
        /// </summary>
        internal static string ReflectionHelper_CantLoadType {
            get {
                return ResourceManager.GetString("ReflectionHelper_CantLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assembly name {0}..
        /// </summary>
        internal static string ReflectionHelper_InvalidAssemblyName {
            get {
                return ResourceManager.GetString("ReflectionHelper_InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid qualified type name {0}..
        /// </summary>
        internal static string ReflectionHelper_InvalidQName {
            get {
                return ResourceManager.GetString("ReflectionHelper_InvalidQName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find assembly {0}..
        /// </summary>
        internal static string TypeResolutionService_AssemblyNotFound {
            get {
                return ResourceManager.GetString("TypeResolutionService_AssemblyNotFound", resourceCulture);
            }
        }
    }
}
