//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.ComponentModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.ComponentModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string ErrorHelper_Abort {
            get {
                return ResourceManager.GetString("ErrorHelper_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string ErrorHelper_Cancel {
            get {
                return ResourceManager.GetString("ErrorHelper_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Framework Error.
        /// </summary>
        internal static string ErrorHelper_Caption {
            get {
                return ResourceManager.GetString("ErrorHelper_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        internal static string ErrorHelper_HideDetails {
            get {
                return ResourceManager.GetString("ErrorHelper_HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        internal static string ErrorHelper_HideDetailsException {
            get {
                return ResourceManager.GetString("ErrorHelper_HideDetailsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string ErrorHelper_Ignore {
            get {
                return ResourceManager.GetString("ErrorHelper_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string ErrorHelper_No {
            get {
                return ResourceManager.GetString("ErrorHelper_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string ErrorHelper_OK {
            get {
                return ResourceManager.GetString("ErrorHelper_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string ErrorHelper_Retry {
            get {
                return ResourceManager.GetString("ErrorHelper_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string ErrorHelper_ShowDetails {
            get {
                return ResourceManager.GetString("ErrorHelper_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string ErrorHelper_ShowDetailsException {
            get {
                return ResourceManager.GetString("ErrorHelper_ShowDetailsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string ErrorHelper_Yes {
            get {
                return ResourceManager.GetString("ErrorHelper_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon2 {
            get {
                object obj = ResourceManager.GetObject("Icon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon3 {
            get {
                object obj = ResourceManager.GetObject("Icon3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon4 {
            get {
                object obj = ResourceManager.GetObject("Icon4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output window created..
        /// </summary>
        internal static string OutputWindowService_InitializedMsg {
            get {
                return ResourceManager.GetString("OutputWindowService_InitializedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Recipe Framework.
        /// </summary>
        internal static string OutputWindowService_WindowName {
            get {
                return ResourceManager.GetString("OutputWindowService_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service instance of type {0} is not assignable to service type {1}..
        /// </summary>
        internal static string ServiceContainer_InvalidServiceInstance {
            get {
                return ResourceManager.GetString("ServiceContainer_InvalidServiceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} already exists in the container..
        /// </summary>
        internal static string ServiceContainer_ServiceExists {
            get {
                return ResourceManager.GetString("ServiceContainer_ServiceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component {0} must be sited in a container in order to function properly..
        /// </summary>
        internal static string ServiceHelper_ComponentNotSited {
            get {
                return ResourceManager.GetString("ServiceHelper_ComponentNotSited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component can not be null..
        /// </summary>
        internal static string ServiceHelper_ComponentNull {
            get {
                return ResourceManager.GetString("ServiceHelper_ComponentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service provider to look for dependencies can not be null..
        /// </summary>
        internal static string ServiceHelper_ProviderNull {
            get {
                return ResourceManager.GetString("ServiceHelper_ProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0}, required for component {1} is not available in the current container..
        /// </summary>
        internal static string ServiceMissingException_Message {
            get {
                return ResourceManager.GetString("ServiceMissingException_Message", resourceCulture);
            }
        }
    }
}
