//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvp.Xml.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mvp.Xml.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #error Couldn&apos;t generate code.
        ////*
        ///{0}
        ///*/.
        /// </summary>
        internal static string CustomTool_GeneralError {
            get {
                return ResourceManager.GetString("CustomTool_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool {0} does not contain the required {1} attribute..
        /// </summary>
        internal static string CustomTool_ToolRequiredAttributeMissing {
            get {
                return ResourceManager.GetString("CustomTool_ToolRequiredAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project must be selected before using this component..
        /// </summary>
        internal static string Dte_NoActiveProject {
            get {
                return ResourceManager.GetString("Dte_NoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent item at location &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string Dte_ParentItemNotFound {
            get {
                return ResourceManager.GetString("Dte_ParentItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &apos;{0}&apos; doesn&apos;t exist in current solution..
        /// </summary>
        internal static string Dte_ProjectDoesntExist {
            get {
                return ResourceManager.GetString("Dte_ProjectDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target project file &apos;{0}&apos; already exists..
        /// </summary>
        internal static string Dte_TargetProjectExists {
            get {
                return ResourceManager.GetString("Dte_TargetProjectExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with path {0} was not found in the current solution..
        /// </summary>
        internal static string DteHelper_InvalidItemPath {
            get {
                return ResourceManager.GetString("DteHelper_InvalidItemPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No element is selected in the solution explorer..
        /// </summary>
        internal static string DteHelper_NoSelection {
            get {
                return ResourceManager.GetString("DteHelper_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Visual Studio solution as well as the Solution Explorer must be opened..
        /// </summary>
        internal static string DteHelper_NoSolutionExplorer {
            get {
                return ResourceManager.GetString("DteHelper_NoSolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is not relative to the solution file &apos;{1}&apos;..
        /// </summary>
        internal static string DteHelper_PathNotRelativeToSln {
            get {
                return ResourceManager.GetString("DteHelper_PathNotRelativeToSln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &apos;{0}&apos; is not a C# or VB.NET project..
        /// </summary>
        internal static string DteHelper_UnsupportedProjectKind {
            get {
                return ResourceManager.GetString("DteHelper_UnsupportedProjectKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component hasn&apos;t been propertly initialized yet..
        /// </summary>
        internal static string Gral_ComponentNotSited {
            get {
                return ResourceManager.GetString("Gral_ComponentNotSited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        internal static string Gral_LanguageCSharp {
            get {
                return ResourceManager.GetString("Gral_LanguageCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB.
        /// </summary>
        internal static string Gral_LanguageVisualBasic {
            get {
                return ResourceManager.GetString("Gral_LanguageVisualBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t perform operation because service &apos;{0}&apos; is not setup properly. Ensure the Microsoft IPE Wizards add-in is loaded..
        /// </summary>
        internal static string Gral_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Gral_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; doesn&apos;t implement required interface &apos;{1}&apos;..
        /// </summary>
        internal static string Gral_TypeMustImplementInterface {
            get {
                return ResourceManager.GetString("Gral_TypeMustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; doesn&apos;t inherit from required base class &apos;{1}&apos;..
        /// </summary>
        internal static string Gral_TypeMustInherit {
            get {
                return ResourceManager.GetString("Gral_TypeMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have the &apos;{1}&apos; attribute..
        /// </summary>
        internal static string Tool_AttributeMissing {
            get {
                return ResourceManager.GetString("Tool_AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project type can&apos;t have code elements, or can&apos;t compile to a .NET language. Supported project types are C# and VB.NET..
        /// </summary>
        internal static string Tool_NoCodeDomSupport {
            get {
                return ResourceManager.GetString("Tool_NoCodeDomSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get current project item..
        /// </summary>
        internal static string Tool_NoDTEProjectItem {
            get {
                return ResourceManager.GetString("Tool_NoDTEProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string Tool_Success {
            get {
                return ResourceManager.GetString("Tool_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output of type CodeDom must be either a CodeNamespace or a CodeCompileUnit..
        /// </summary>
        internal static string Tool_UnsupportedCodeDomOutput {
            get {
                return ResourceManager.GetString("Tool_UnsupportedCodeDomOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project type is unsupported for this tool..
        /// </summary>
        internal static string Tool_UnsupportedProjectType {
            get {
                return ResourceManager.GetString("Tool_UnsupportedProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected element doesn&apos;t contain any class definitions..
        /// </summary>
        internal static string XGenTool_NoClassFound {
            get {
                return ResourceManager.GetString("XGenTool_NoClassFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #warning Containing project could not be compiled successfully. Generated code may be outdated.
        ///.
        /// </summary>
        internal static string XGenTool_ProjectDoesNotCompile {
            get {
                return ResourceManager.GetString("XGenTool_ProjectDoesNotCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a matching closing bracket in input string..
        /// </summary>
        internal static string XGenTool_UnclosedBrackets {
            get {
                return ResourceManager.GetString("XGenTool_UnclosedBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed. Errors:
        ///{0}.
        /// </summary>
        internal static string XmlValidate_Failed {
            get {
                return ResourceManager.GetString("XmlValidate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t process XML file:
        ///{0}.
        /// </summary>
        internal static string XmlValidate_GeneralError {
            get {
                return ResourceManager.GetString("XmlValidate_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location for the schema was specified. Set an absolute or XML file-relative location for the schema in the Custom Tool Namespace property for the file..
        /// </summary>
        internal static string XmlValidate_NoSchemaLocation {
            get {
                return ResourceManager.GetString("XmlValidate_NoSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation succeeded..
        /// </summary>
        internal static string XmlValidate_Succeeded {
            get {
                return ResourceManager.GetString("XmlValidate_Succeeded", resourceCulture);
            }
        }
    }
}
