//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.WizardFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.WizardFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component is already initialized.
        /// </summary>
        internal static string Component_Already_Initialized {
            get {
                return ResourceManager.GetString("Component_Already_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert value from type {0} to type {1}.
        /// </summary>
        internal static string ValueEditor_CantConvertValue {
            get {
                return ResourceManager.GetString("ValueEditor_CantConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        internal static string ValueEditor_InvalidValue {
            get {
                return ResourceManager.GetString("ValueEditor_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use a List Box without a TypeConverter.
        /// </summary>
        internal static string ValueEditor_ListBoxWithOutTypeConverter {
            get {
                return ResourceManager.GetString("ValueEditor_ListBoxWithOutTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ValueEditor_ValueNull {
            get {
                return ResourceManager.GetString("ValueEditor_ValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        internal static string ValueEditor_ValueNullCaption {
            get {
                return ResourceManager.GetString("ValueEditor_ValueNullCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create WizardPage {0}, {1}..
        /// </summary>
        internal static string Wizard_CannotCreateStep {
            get {
                return ResourceManager.GetString("Wizard_CannotCreateStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard {0} cannot complete execution.
        /// </summary>
        internal static string WizardGatheringService_CannotExecuteWizard {
            get {
                return ResourceManager.GetString("WizardGatheringService_CannotExecuteWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to display {0} help resource..
        /// </summary>
        internal static string WizardGatheringService_CannotGetHelpResource {
            get {
                return ResourceManager.GetString("WizardGatheringService_CannotGetHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load Wizard configuration.
        /// </summary>
        internal static string WizardGatheringService_CannotLoadConfig {
            get {
                return ResourceManager.GetString("WizardGatheringService_CannotLoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type for argument {0} in page {1} cannot be loaded. Cannot continue..
        /// </summary>
        internal static string WizardGatheringService_CannotLoadTypeStepField {
            get {
                return ResourceManager.GetString("WizardGatheringService_CannotLoadTypeStepField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set property {0} from Custom Page {1}..
        /// </summary>
        internal static string WizardGatheringService_CannotSetProperty {
            get {
                return ResourceManager.GetString("WizardGatheringService_CannotSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wizard {0} failed to execute. The error was:
        ///{1}.
        /// </summary>
        internal static string WizardGatheringService_ExecutionFailed {
            get {
                return ResourceManager.GetString("WizardGatheringService_ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument {0} is already collected by the step {1}. It cannot be added to step {2}..
        /// </summary>
        internal static string WizardGatheringService_InvalidArgForStepField {
            get {
                return ResourceManager.GetString("WizardGatheringService_InvalidArgForStepField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Wizard configuration.
        /// </summary>
        internal static string WizardGatheringService_InvalidConfiguration {
            get {
                return ResourceManager.GetString("WizardGatheringService_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta data for argument {0} cannot be found. Cannot continue..
        /// </summary>
        internal static string WizardGatheringService_MissingArgumentMetaData {
            get {
                return ResourceManager.GetString("WizardGatheringService_MissingArgumentMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wizard requires Fields description.
        /// </summary>
        internal static string WizardGatheringService_MissingFields {
            get {
                return ResourceManager.GetString("WizardGatheringService_MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration service was not found and it&apos;s required..
        /// </summary>
        internal static string WizardGatheringService_NoConfigurationService {
            get {
                return ResourceManager.GetString("WizardGatheringService_NoConfigurationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration service does not have a current wizard to run..
        /// </summary>
        internal static string WizardGatheringService_NoCurrentWizard {
            get {
                return ResourceManager.GetString("WizardGatheringService_NoCurrentWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown step.
        /// </summary>
        internal static string WizardGatheringService_UnknownStep {
            get {
                return ResourceManager.GetString("WizardGatheringService_UnknownStep", resourceCulture);
            }
        }
    }
}
