//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.RecipeFramework.MetaGuidancePackage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.RecipeFramework.MetaGuidancePackage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This recipe will set the ‘Copy to Output’ property to ‘Copy if newer’
        ///and the ‘Build Action’ property to ‘Content’ for all project items.
        ///Would you like to continue?.
        /// </summary>
        internal static string Actions_ItemsBuildProps_Confirmation {
            get {
                return ResourceManager.GetString("Actions_ItemsBuildProps_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Items’ Build Properties: Completed Failed. No SubItems to apply the settings.
        /// </summary>
        internal static string Actions_ItemsBuildProps_Fail {
            get {
                return ResourceManager.GetString("Actions_ItemsBuildProps_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying settings to all sub items of folder {0}.
        /// </summary>
        internal static string Actions_ItemsBuildProps_Progress {
            get {
                return ResourceManager.GetString("Actions_ItemsBuildProps_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Items’ Build Properties: Completed Successfully.
        /// </summary>
        internal static string Actions_ItemsBuildProps_Success {
            get {
                return ResourceManager.GetString("Actions_ItemsBuildProps_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Items&apos; Build Properties.
        /// </summary>
        internal static string Actions_ItemsBuildProps_Title {
            get {
                return ResourceManager.GetString("Actions_ItemsBuildProps_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation: {0}.
        /// </summary>
        internal static string CredUIReturn {
            get {
                return ResourceManager.GetString("CredUIReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project is currently selected..
        /// </summary>
        internal static string Dte_NoProjectSelected {
            get {
                return ResourceManager.GetString("Dte_NoProjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing action {0}.
        /// </summary>
        internal static string ExecutingAction {
            get {
                return ResourceManager.GetString("ExecutingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Credential Management API requires Windows XP / Windows Server 2003 or later..
        /// </summary>
        internal static string FunctionNotSupported {
            get {
                return ResourceManager.GetString("FunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caption has a maximum length of {0} characters..
        /// </summary>
        internal static string InvalidCaptionLength {
            get {
                return ResourceManager.GetString("InvalidCaptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Condition {0}/n{1}.
        /// </summary>
        internal static string InvalidConditionException {
            get {
                return ResourceManager.GetString("InvalidConditionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The banner image height must be {0} pixels..
        /// </summary>
        internal static string InvalidImageHeight {
            get {
                return ResourceManager.GetString("InvalidImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The banner image width must be {0} pixels..
        /// </summary>
        internal static string InvalidImageWidth {
            get {
                return ResourceManager.GetString("InvalidImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has a maximum length of {0} characters..
        /// </summary>
        internal static string InvalidMessageLength {
            get {
                return ResourceManager.GetString("InvalidMessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project {0} is not a valid Guidance Package project.
        /// </summary>
        internal static string InvalidPackageProject {
            get {
                return ResourceManager.GetString("InvalidPackageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has a maximum length of {0} characters..
        /// </summary>
        internal static string InvalidPasswordLength {
            get {
                return ResourceManager.GetString("InvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The principal name has a maximum length of {0} characters..
        /// </summary>
        internal static string InvalidPrincipalLength {
            get {
                return ResourceManager.GetString("InvalidPrincipalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target has a maximum length of {0} characters..
        /// </summary>
        internal static string InvalidTargetLength {
            get {
                return ResourceManager.GetString("InvalidTargetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0} is not registered..
        /// </summary>
        internal static string PackageProjectNotRegistered {
            get {
                return ResourceManager.GetString("PackageProjectNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials dialog cancelled by the user. Administrator credentials required to perform action..
        /// </summary>
        internal static string Registration_CredentialsDialogCancelled {
            get {
                return ResourceManager.GetString("Registration_CredentialsDialogCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires administrator permissions. Please provide alternate credentials..
        /// </summary>
        internal static string Registration_CredentialsPrompt {
            get {
                return ResourceManager.GetString("Registration_CredentialsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Guidance Automation.
        /// </summary>
        internal static string Registration_CredentialsTitle {
            get {
                return ResourceManager.GetString("Registration_CredentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process package. See the Guidance Package Development output window for more information about the error..
        /// </summary>
        internal static string Registration_Failed {
            get {
                return ResourceManager.GetString("Registration_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of Package failed..
        /// </summary>
        internal static string Registration_FailedStatus {
            get {
                return ResourceManager.GetString("Registration_FailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of Package in progress... This may take a while, please be patient.
        /// </summary>
        internal static string Registration_InProgress {
            get {
                return ResourceManager.GetString("Registration_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance package registration depends on an installer project. The package project must have a build dependency with that project, and the installer project must contain a class that inherits from the {0} class..
        /// </summary>
        internal static string Registration_InstallerProjectNotFound {
            get {
                return ResourceManager.GetString("Registration_InstallerProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified &apos;{0}&apos; registration setting is not valid.
        /// </summary>
        internal static string Registration_InvalidHive {
            get {
                return ResourceManager.GetString("Registration_InvalidHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4}{3}User: {0}\{1}.{3}Machine: {5}{3}Check if user has {2} privileges enabled or if running under Windows 2000, the privilege &apos;Act as part of the operating system&apos; enabled for user {6}..
        /// </summary>
        internal static string Registration_LogonUserException {
            get {
                return ResourceManager.GetString("Registration_LogonUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of packages running as a non-administrator user is only supported in Windows XP, Windows 2003 or greater..
        /// </summary>
        internal static string Registration_NonAdminOnOldPlatform {
            get {
                return ResourceManager.GetString("Registration_NonAdminOnOldPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no XML file under the project that defines a guidance package..
        /// </summary>
        internal static string Registration_NoPackageConfig {
            get {
                return ResourceManager.GetString("Registration_NoPackageConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick registration.
        /// </summary>
        internal static string Registration_QuickRegistration {
            get {
                return ResourceManager.GetString("Registration_QuickRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick registration finished..
        /// </summary>
        internal static string Registration_QuickRegistrationDone {
            get {
                return ResourceManager.GetString("Registration_QuickRegistrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick registration failed..
        /// </summary>
        internal static string Registration_QuickRegistrationFailed {
            get {
                return ResourceManager.GetString("Registration_QuickRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration_RegistrationText {
            get {
                return ResourceManager.GetString("Registration_RegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of Package succeeded..
        /// </summary>
        internal static string Registration_SucceedStatus {
            get {
                return ResourceManager.GetString("Registration_SucceedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistration.
        /// </summary>
        internal static string Registration_UnregistrationText {
            get {
                return ResourceManager.GetString("Registration_UnregistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Actions....
        /// </summary>
        internal static string StatusBarProgressMessage {
            get {
                return ResourceManager.GetString("StatusBarProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non VSIX Guidance package project.
        /// </summary>
        internal static string UnboundNonVsixPackageReference_AppliesTo {
            get {
                return ResourceManager.GetString("UnboundNonVsixPackageReference_AppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance package project.
        /// </summary>
        internal static string UnboundPackageReference_AppliesTo {
            get {
                return ResourceManager.GetString("UnboundPackageReference_AppliesTo", resourceCulture);
            }
        }
    }
}
