//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.RecipeFramework.VisualStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.RecipeFramework.VisualStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _301 {
            get {
                object obj = ResourceManager.GetObject("301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced item {0} does not exist in the current solution. .
        /// </summary>
        internal static string BoundReference_InvalidItem {
            get {
                return ResourceManager.GetString("BoundReference_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Guidance Package configuration file could not be found: &apos;{0}&apos;.
        /// </summary>
        internal static string Build_GuidancePackageConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("Build_GuidancePackageConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSIX manifest must define one Guidance Package custom extension.
        /// </summary>
        internal static string Build_GuidancePackageCustomExtensionNotFound {
            get {
                return ResourceManager.GetString("Build_GuidancePackageCustomExtensionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot check out {0} file..
        /// </summary>
        internal static string Checkout_Failed {
            get {
                return ResourceManager.GetString("Checkout_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced command bar {0} cannot be found, check your configuration..
        /// </summary>
        internal static string CommandBar_NotFound {
            get {
                return ResourceManager.GetString("CommandBar_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CTC_LabelUnknown {
            get {
                return ResourceManager.GetString("CTC_LabelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu group {0} does not exist..
        /// </summary>
        internal static string CTC_MenuDoesNotExist {
            get {
                return ResourceManager.GetString("CTC_MenuDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command bar {0} already used in this command..
        /// </summary>
        internal static string CTC_RepeatedCommandBar {
            get {
                return ResourceManager.GetString("CTC_RepeatedCommandBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} must have a {1} attribute..
        /// </summary>
        internal static string General_AttributeMissing {
            get {
                return ResourceManager.GetString("General_AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} doesn&apos;t implement required interface {1}..
        /// </summary>
        internal static string General_TypeMustImplement {
            get {
                return ResourceManager.GetString("General_TypeMustImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} doesn&apos;t inherit from required base class {1}..
        /// </summary>
        internal static string General_TypeMustInheritFrom {
            get {
                return ResourceManager.GetString("General_TypeMustInheritFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create Guidance Navigator Window.
        /// </summary>
        internal static string GuidanceNavigatorWindow_CannotCreate {
            get {
                return ResourceManager.GetString("GuidanceNavigatorWindow_CannotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance Package Manager....
        /// </summary>
        internal static string GuidanceNavigatorWindow_GuidancePackageManagerOptionText {
            get {
                return ResourceManager.GetString("GuidanceNavigatorWindow_GuidancePackageManagerOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance Navigator.
        /// </summary>
        internal static string GuidanceNavigatorWindow_Title {
            get {
                return ResourceManager.GetString("GuidanceNavigatorWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Project.
        /// </summary>
        internal static string IDD_ADDPROJECTDLG {
            get {
                return ResourceManager.GetString("IDD_ADDPROJECTDLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string IDD_NEWPROJECTDLG {
            get {
                return ResourceManager.GetString("IDD_NEWPROJECTDLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user cancelled the creation of the {0}.
        /// </summary>
        internal static string Item_CreationAborted {
            get {
                return ResourceManager.GetString("Item_CreationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred creating the {0}.
        /// </summary>
        internal static string Item_CreationFailed {
            get {
                return ResourceManager.GetString("Item_CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Item_Project {
            get {
                return ResourceManager.GetString("Item_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project item.
        /// </summary>
        internal static string Item_ProjectItem {
            get {
                return ResourceManager.GetString("Item_ProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string Item_Solution {
            get {
                return ResourceManager.GetString("Item_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot continue with installation until DefaultRegistryRootAttribute is used.
        /// </summary>
        internal static string Missing_RegRoot {
            get {
                return ResourceManager.GetString("Missing_RegRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while trying to get the {0} string resource from {1}.
        /// </summary>
        internal static string NativeMethods_GetStringResourceException {
            get {
                return ResourceManager.GetString("NativeMethods_GetStringResourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to display {0} help resource..
        /// </summary>
        internal static string Navigator_CannotGetHelpResource {
            get {
                return ResourceManager.GetString("Navigator_CannotGetHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Next Steps:.
        /// </summary>
        internal static string Navigator_NextStepsTitle {
            get {
                return ResourceManager.GetString("Navigator_NextStepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference {0} throw an exception: {1}.\n.
        /// </summary>
        internal static string Navigator_ReferenceThrowException {
            get {
                return ResourceManager.GetString("Navigator_ReferenceThrowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this recipe.
        /// </summary>
        internal static string Navigator_RunThisRecipe {
            get {
                return ResourceManager.GetString("Navigator_RunThisRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this recipe again.
        /// </summary>
        internal static string Navigator_RunThisRecipeAgain {
            get {
                return ResourceManager.GetString("Navigator_RunThisRecipeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item you selected is not available anymore. Please press OK to refresh the list of available guidance..
        /// </summary>
        internal static string Navigator_StaleReference {
            get {
                return ResourceManager.GetString("Navigator_StaleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Navigator_StaleReferenceTitle {
            get {
                return ResourceManager.GetString("Navigator_StaleReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string Navigator_TemplateCaptionMask {
            get {
                return ResourceManager.GetString("Navigator_TemplateCaptionMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold this template.
        /// </summary>
        internal static string Navigator_UnfoldThisTemplate {
            get {
                return ResourceManager.GetString("Navigator_UnfoldThisTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve the recipe manager service..
        /// </summary>
        internal static string Package_CantGetManagerService {
            get {
                return ResourceManager.GetString("Package_CantGetManagerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Recipe Framework package..
        /// </summary>
        internal static string Package_FailedToLoad {
            get {
                return ResourceManager.GetString("Package_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solution must be opened to run the guidance package manager..
        /// </summary>
        internal static string Package_NoSolutionOpened {
            get {
                return ResourceManager.GetString("Package_NoSolutionOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0} doesn&apos;t have the Guid attribute required to install on the Visual Studio host..
        /// </summary>
        internal static string Package_PackageNeedsGuid {
            get {
                return ResourceManager.GetString("Package_PackageNeedsGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} is not found. Cannot continue..
        /// </summary>
        internal static string Package_ServiceRequired {
            get {
                return ResourceManager.GetString("Package_ServiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item at: {1}.
        /// </summary>
        internal static string ProjectItemReference_AppliesTo {
            get {
                return ResourceManager.GetString("ProjectItemReference_AppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project at: {0}.
        /// </summary>
        internal static string ProjectReference_AppliesTo {
            get {
                return ResourceManager.GetString("ProjectReference_AppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of recipes must not exceed a maximum of 256..
        /// </summary>
        internal static string Recipes_MaximumExceeded {
            get {
                return ResourceManager.GetString("Recipes_MaximumExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppliesTo method threw an exception.
        /// </summary>
        internal static string Reference_AppliesToThrew {
            get {
                return ResourceManager.GetString("Reference_AppliesToThrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to: {0}.
        /// </summary>
        internal static string Reference_AppliesToTooltip {
            get {
                return ResourceManager.GetString("Reference_AppliesToTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function IsEnabledFor is not correctly implemented because it threw an exception.
        /// </summary>
        internal static string Reference_FailEnabledFor {
            get {
                return ResourceManager.GetString("Reference_FailEnabledFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference has not correctly implemented some attributes because one or some of them threw an exception. The failure ocurred in the attribute(s): {0}.
        /// </summary>
        internal static string Reference_InvalidAttributes {
            get {
                return ResourceManager.GetString("Reference_InvalidAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cancelled the restoring of the references.
        ///If you continue all the references will be deleted.
        ///Do you want to try again the reconnection of the references?.
        /// </summary>
        internal static string ReferenceRestoreService_Cancelled {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve disconnected references to recipes or templates.
        /// </summary>
        internal static string ReferenceRestoreService_DialogTitle {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to reconnect the references.
        /// </summary>
        internal static string ReferenceRestoreService_Error {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the reference to {0}.
        /// </summary>
        internal static string ReferenceRestoreService_FieldCheckTooltip {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_FieldCheckTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected target must be of kind {0}..
        /// </summary>
        internal static string ReferenceRestoreService_FieldInvalid {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_FieldInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element of type {0} should be selected for the recipe {1}.
        /// </summary>
        internal static string ReferenceRestoreService_FieldRecipeHelp {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_FieldRecipeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element of type {0} should be selected for the template with 
        ///the relative path as {1}.
        /// </summary>
        internal static string ReferenceRestoreService_FieldTemplateHelp {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_FieldTemplateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target was originally at {0}, 
        ///and its expected type is {1}..
        /// </summary>
        internal static string ReferenceRestoreService_FieldTooltip {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_FieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The displayed references to recipes or templates have become disconnected from their original solution elements. For each reference, you can choose to delete it, or specify the solution element that is should be reattached to..
        /// </summary>
        internal static string ReferenceRestoreService_PageHelp {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_PageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References {0}/{1}.
        /// </summary>
        internal static string ReferenceRestoreService_PageLinkTitle {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_PageLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the new targets for the disconnected references [Page {0}/{1}].
        /// </summary>
        internal static string ReferenceRestoreService_PageTitle {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Recipe: {0} pointed to {1}
        ///.
        /// </summary>
        internal static string ReferenceRestoreService_RecipeOldPath {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_RecipeOldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;move.
        /// </summary>
        internal static string ReferenceRestoreService_RemoveButton {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;solve.
        /// </summary>
        internal static string ReferenceRestoreService_ResolveButton {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_ResolveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution contains a reference to a recipe or template, but
        ///the solution item that contained the reference have changed or no longer exist.
        ///{0}
        ///Would you like to remove the reference and continue to load the solution,
        ///or try to resolve the reference by reattaching it?.
        /// </summary>
        internal static string ReferenceRestoreService_StartDanglingReference {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_StartDanglingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution contains references to recipes or templates, but
        ///the solution items that contained the references have changed or no longer exist.
        ///{0} 
        ///Would you like to remove the references and continue to load the solution,
        ///or try to resolve the references by reattaching them?.
        /// </summary>
        internal static string ReferenceRestoreService_StartDanglingReferences {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_StartDanglingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution contains disconnected references to recipes or templates.
        /// </summary>
        internal static string ReferenceRestoreService_StartTitle {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_StartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Template: {0} pointed to {1}
        ///.
        /// </summary>
        internal static string ReferenceRestoreService_TemplateOldPath {
            get {
                return ResourceManager.GetString("ReferenceRestoreService_TemplateOldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find guidance package name &apos;{0}&apos; with Guid &apos;{1}&apos;..
        /// </summary>
        internal static string Registration_CannotFindGuidancePackage {
            get {
                return ResourceManager.GetString("Registration_CannotFindGuidancePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find registry key &apos;{0}&apos; in hive &apos;{1}&apos;..
        /// </summary>
        internal static string Registration_CannotFindRegistryKey {
            get {
                return ResourceManager.GetString("Registration_CannotFindRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open source registry hive &apos;{0}&apos;..
        /// </summary>
        internal static string Registration_CannotFindSourceHive {
            get {
                return ResourceManager.GetString("Registration_CannotFindSourceHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open target registry hive &apos;{0}&apos;..
        /// </summary>
        internal static string Registration_CannotFindTargetHive {
            get {
                return ResourceManager.GetString("Registration_CannotFindTargetHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve embedded GAX registration file.
        /// </summary>
        internal static string Registration_CannotRetrieveGaxRegFile {
            get {
                return ResourceManager.GetString("Registration_CannotRetrieveGaxRegFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of GAX into VS experimental hive failed..
        /// </summary>
        internal static string Registration_FailedGaxRegistrationIntoExpHive {
            get {
                return ResourceManager.GetString("Registration_FailedGaxRegistrationIntoExpHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance Package {0} failed to load. Do you want to permanently remove the package from the current solution?.
        /// </summary>
        internal static string SolutionPackagesContainer_CannotLoadPackage {
            get {
                return ResourceManager.GetString("SolutionPackagesContainer_CannotLoadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Do you want to permanently remove the package from the current solution?.
        /// </summary>
        internal static string SolutionPackagesContainer_PackageRemovePersistence {
            get {
                return ResourceManager.GetString("SolutionPackagesContainer_PackageRemovePersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the package {0} enabled for the solution
        ///is different than the one currently installed.
        ///Therefore if the binding recipe is specified in the package 
        ///configuration file it will be executed again..
        /// </summary>
        internal static string SolutionPackagesContainer_PackageVersionDiffers {
            get {
                return ResourceManager.GetString("SolutionPackagesContainer_PackageVersionDiffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Version.
        /// </summary>
        internal static string SolutionPackagesContainer_PackageVersionDiffersTitle {
            get {
                return ResourceManager.GetString("SolutionPackagesContainer_PackageVersionDiffersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot finish restoring of original bound references..
        /// </summary>
        internal static string SolutionPackagesContainer_RestoringFailed {
            get {
                return ResourceManager.GetString("SolutionPackagesContainer_RestoringFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error loading property {0}.
        /// </summary>
        internal static string SolutionPackagesContainer_SerializationError {
            get {
                return ResourceManager.GetString("SolutionPackagesContainer_SerializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating reference to {0} from package {1}.
        /// </summary>
        internal static string SolutionPackagesContainer_UpdatingReference {
            get {
                return ResourceManager.GetString("SolutionPackagesContainer_UpdatingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either an unbound asset reference or the target element type must be provided..
        /// </summary>
        internal static string SolutionPicker_NullRefAndType {
            get {
                return ResourceManager.GetString("SolutionPicker_NullRefAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string SolutionPicker_ReferencesNode {
            get {
                return ResourceManager.GetString("SolutionPicker_ReferencesNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution root.
        /// </summary>
        internal static string SolutionReference_AppliesTo {
            get {
                return ResourceManager.GetString("SolutionReference_AppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register task list provider..
        /// </summary>
        internal static string TaskList_CannotRegister {
            get {
                return ResourceManager.GetString("TaskList_CannotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string TaskList_ColumnName {
            get {
                return ResourceManager.GetString("TaskList_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TaskList_Description {
            get {
                return ResourceManager.GetString("TaskList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound To.
        /// </summary>
        internal static string TaskList_ProjectItem {
            get {
                return ResourceManager.GetString("TaskList_ProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filename specified for the template &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string Template_DoesntExist {
            get {
                return ResourceManager.GetString("Template_DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring invalid initial state with key {0} for reference that applies to {1}..
        /// </summary>
        internal static string Template_IgnoreKeyInitialState {
            get {
                return ResourceManager.GetString("Template_IgnoreKeyInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} is already been used by another package, only one folder will be used..
        /// </summary>
        internal static string Template_MultipleTemplateDirs {
            get {
                return ResourceManager.GetString("Template_MultipleTemplateDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TemplateReference_Category {
            get {
                return ResourceManager.GetString("TemplateReference_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is defined in both recipe {1} and recipe {2}. Shared arguments are not supported when unfolding a multi project template..
        /// </summary>
        internal static string Templates_ArgumentsShared {
            get {
                return ResourceManager.GetString("Templates_ArgumentsShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load recipe manager service. Cannot continue..
        /// </summary>
        internal static string Templates_CannotLoadRecipeManager {
            get {
                return ResourceManager.GetString("Templates_CannotLoadRecipeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target {0} specified for reference to asset {1} doesn&apos;t exist..
        /// </summary>
        internal static string Templates_CantFindTarget {
            get {
                return ResourceManager.GetString("Templates_CantFindTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors happened when trying to create the asset references: {0}.
        /// </summary>
        internal static string Templates_CantFindTargets {
            get {
                return ResourceManager.GetString("Templates_CantFindTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates_Category {
            get {
                return ResourceManager.GetString("Templates_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}....
        /// </summary>
        internal static string Templates_ContextMenu {
            get {
                return ResourceManager.GetString("Templates_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry is corrupt, multiple project factories found for language {0}.
        /// </summary>
        internal static string Templates_CorruptMultipleFactories {
            get {
                return ResourceManager.GetString("Templates_CorruptMultipleFactories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors processing the references in the template {0}..
        /// </summary>
        internal static string Templates_ErrorsProcessingReferences {
            get {
                return ResourceManager.GetString("Templates_ErrorsProcessingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial state for asset named &quot;{0}&quot; with target &quot;{1}&quot; is invalid and will be removed..
        /// </summary>
        internal static string Templates_InitialStateError {
            get {
                return ResourceManager.GetString("Templates_InitialStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item template {0} cannot be unfolded under the project {1}. Invalid item template is {0}..
        /// </summary>
        internal static string Templates_InvalidProjectForItemTemplate {
            get {
                return ResourceManager.GetString("Templates_InvalidProjectForItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registry found {0}, it should be a GUID.
        /// </summary>
        internal static string Templates_InvalidRegistry {
            get {
                return ResourceManager.GetString("Templates_InvalidRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error loading template file name {0}. Make sure that the template is well formed and try again..
        /// </summary>
        internal static string Templates_InvalidTemplateFile {
            get {
                return ResourceManager.GetString("Templates_InvalidTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item template {0} with project type element set to {1} in the template file cannot be unfolded under the solution folder {2}. Only the item templates with element value set to &quot;General&quot; are allowed to be unfolded under solution folders..
        /// </summary>
        internal static string Templates_InvalidTypeItemForSolutionFolder {
            get {
                return ResourceManager.GetString("Templates_InvalidTypeItemForSolutionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template configuration is missing or invalid, cannot continue..
        /// </summary>
        internal static string Templates_InvalidWizardData {
            get {
                return ResourceManager.GetString("Templates_InvalidWizardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution root cannot have item template references. Invalid item template is {0}..
        /// </summary>
        internal static string Templates_ItemCannotBeRoot {
            get {
                return ResourceManager.GetString("Templates_ItemCannotBeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item cannot have template references. Invalid template is {0}..
        /// </summary>
        internal static string Templates_ItemCantHaveTemplates {
            get {
                return ResourceManager.GetString("Templates_ItemCantHaveTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference target {0} specified in item template {1} is invalid, as it must always be the string &quot;\&quot;. Item templates can only point to the item itself..
        /// </summary>
        internal static string Templates_ItemTargetInvalid {
            get {
                return ResourceManager.GetString("Templates_ItemTargetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template {0} is not compatible with template {1}..
        /// </summary>
        internal static string Templates_KindMismatch {
            get {
                return ResourceManager.GetString("Templates_KindMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of templates must not exceed a maximum of 256..
        /// </summary>
        internal static string Templates_MaximumExceeded {
            get {
                return ResourceManager.GetString("Templates_MaximumExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .vstemplate file does not contain a VSTemplate/@Type attribute, so the type of the template is indeterminate..
        /// </summary>
        internal static string Templates_MissingType {
            get {
                return ResourceManager.GetString("Templates_MissingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template does not have the correct WizardExtension data..
        /// </summary>
        internal static string Templates_NoExtension {
            get {
                return ResourceManager.GetString("Templates_NoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find registration information for template &quot;{0}&quot;. Package templates may not be properly registered. Run package installation again and verify template name and location..
        /// </summary>
        internal static string Templates_NotRegistered {
            get {
                return ResourceManager.GetString("Templates_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package {0} could not activated, the template cannot be unfolded..
        /// </summary>
        internal static string Templates_PackageNotActive {
            get {
                return ResourceManager.GetString("Templates_PackageNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project factory {0} is not registered, template {1} cannot be installed..
        /// </summary>
        internal static string Templates_ProjectFactoryNotFound {
            get {
                return ResourceManager.GetString("Templates_ProjectFactoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project template {0} can only be unfolded under project solution folders and not under project {1}. Invalid template is {0}..
        /// </summary>
        internal static string Templates_ProjectInvalidReference {
            get {
                return ResourceManager.GetString("Templates_ProjectInvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution templates cannot be bound to any element. Invalid template is {0}..
        /// </summary>
        internal static string Templates_SolutionCannotBeBound {
            get {
                return ResourceManager.GetString("Templates_SolutionCannotBeBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template can&apos;t be executed given the current selection..
        /// </summary>
        internal static string Templates_TemplateNotEnabled {
            get {
                return ResourceManager.GetString("Templates_TemplateNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file not found..
        /// </summary>
        internal static string Templates_TemplateNotFound {
            get {
                return ResourceManager.GetString("Templates_TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type {0} must not have a ProgId attribute.
        /// </summary>
        internal static string Type_AlreadyContainsProgId {
            get {
                return ResourceManager.GetString("Type_AlreadyContainsProgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All solution elements.
        /// </summary>
        internal static string UnboundReference_AllItems {
            get {
                return ResourceManager.GetString("UnboundReference_AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web project {0} is file system-based, and it is not located in a folder under the solution. References will be connected to the full path of the website. If the site is moved, the references will need to be reconnected..
        /// </summary>
        internal static string WebProjectReference_FileSystemWebNotUnderSolution {
            get {
                return ResourceManager.GetString("WebProjectReference_FileSystemWebNotUnderSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is not a web site project..
        /// </summary>
        internal static string WebProjectReference_InvalidProject {
            get {
                return ResourceManager.GetString("WebProjectReference_InvalidProject", resourceCulture);
            }
        }
    }
}
